//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int idInvoice { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idBike { get; set; }
        public Nullable<int> idPayment { get; set; }
        public Nullable<double> totalHours { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<System.TimeSpan> invoiceTime { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
    }
}
