//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolMenu
    {
        public int idRolMenu { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idMenu { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
