//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int idUsers { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> idRol { get; set; }
        public string password { get; set; }
        public byte[] photo { get; set; }
        public byte[] cnicFront { get; set; }
        public byte[] cnicBack { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
